package com.bwf.aiyiqi.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwf.aiyiqi.entity.GreenDaoDb;

import com.bwf.aiyiqi.entity.GreenDaoDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoDbDaoConfig;

    private final GreenDaoDbDao greenDaoDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoDbDaoConfig = daoConfigMap.get(GreenDaoDbDao.class).clone();
        greenDaoDbDaoConfig.initIdentityScope(type);

        greenDaoDbDao = new GreenDaoDbDao(greenDaoDbDaoConfig, this);

        registerDao(GreenDaoDb.class, greenDaoDbDao);
    }
    
    public void clear() {
        greenDaoDbDaoConfig.clearIdentityScope();
    }

    public GreenDaoDbDao getGreenDaoDbDao() {
        return greenDaoDbDao;
    }

}
